CREATE DATABASE IF NOT EXISTS VOLTSENSE;

CREATE SCHEMA IF NOT EXISTS VOLTSENSE.RAW;
CREATE SCHEMA IF NOT EXISTS VOLTSENSE.STAGING;
CREATE SCHEMA IF NOT EXISTS VOLTSENSE.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS VOLTSENSE.MARTS;
CREATE SCHEMA IF NOT EXISTS VOLTSENSE.ML_FEATURES;

CREATE WAREHOUSE IF NOT EXISTS VOLTSENSE_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE DATABASE VOLTSENSE;
USE WAREHOUSE VOLTSENSE_WH;

CREATE OR REPLACE TABLE VOLTSENSE.RAW.RAW_CHARGER_SESSIONS (
    RECORD_CONTENT VARIANT,
    RECORD_METADATA VARIANT
);

CREATE OR REPLACE TABLE VOLTSENSE.RAW.RAW_WEATHER_READINGS (
    RECORD_CONTENT VARIANT,
    RECORD_METADATA VARIANT
);

CREATE OR REPLACE TABLE VOLTSENSE.RAW.RAW_GRID_PRICING (
    RECORD_CONTENT VARIANT,
    RECORD_METADATA VARIANT
);

CREATE OR REPLACE TABLE VOLTSENSE.RAW.FACT_PREDICTIONS_RAW (
    STATION_ID VARCHAR,
    PREDICTION_TIMESTAMP TIMESTAMP_NTZ,
    PREDICTED_UTILIZATION_PCT FLOAT,
    PREDICTION_LOWER_80 FLOAT,
    PREDICTION_UPPER_80 FLOAT,
    MODEL_VERSION VARCHAR,
    PREDICTED_AT TIMESTAMP_NTZ
);